//
// Created by Evgeny on 12/16/2015.
//

#ifndef PASCALVARIABLEDECLARATION_FILEHANDLE_H
#define PASCALVARIABLEDECLARATION_FILEHANDLE_H

#endif //PASCALVARIABLEDECLARATION_FILEHANDLE_H

char * read_text_from_file(char * fileName);
